// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: nodes_api.proto

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodesCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ipv4Address    string `protobuf:"bytes,1,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	Fqdn           string `protobuf:"bytes,2,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	SkyhookVersion string `protobuf:"bytes,3,opt,name=skyhook_version,json=skyhookVersion,proto3" json:"skyhook_version,omitempty"`
	Os             string `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Cpu            string `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	CpuBaseClock   uint32 `protobuf:"varint,6,opt,name=cpu_base_clock,json=cpuBaseClock,proto3" json:"cpu_base_clock,omitempty"`
	Cores          uint32 `protobuf:"varint,7,opt,name=cores,proto3" json:"cores,omitempty"`
	LogicalCores   uint32 `protobuf:"varint,8,opt,name=logical_cores,json=logicalCores,proto3" json:"logical_cores,omitempty"`
	Ram            uint32 `protobuf:"varint,9,opt,name=ram,proto3" json:"ram,omitempty"`
	Storage        uint32 `protobuf:"varint,10,opt,name=storage,proto3" json:"storage,omitempty"`
}

func (x *NodesCreateRequest) Reset() {
	*x = NodesCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodes_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodesCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesCreateRequest) ProtoMessage() {}

func (x *NodesCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesCreateRequest.ProtoReflect.Descriptor instead.
func (*NodesCreateRequest) Descriptor() ([]byte, []int) {
	return file_nodes_api_proto_rawDescGZIP(), []int{0}
}

func (x *NodesCreateRequest) GetIpv4Address() string {
	if x != nil {
		return x.Ipv4Address
	}
	return ""
}

func (x *NodesCreateRequest) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *NodesCreateRequest) GetSkyhookVersion() string {
	if x != nil {
		return x.SkyhookVersion
	}
	return ""
}

func (x *NodesCreateRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *NodesCreateRequest) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *NodesCreateRequest) GetCpuBaseClock() uint32 {
	if x != nil {
		return x.CpuBaseClock
	}
	return 0
}

func (x *NodesCreateRequest) GetCores() uint32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *NodesCreateRequest) GetLogicalCores() uint32 {
	if x != nil {
		return x.LogicalCores
	}
	return 0
}

func (x *NodesCreateRequest) GetRam() uint32 {
	if x != nil {
		return x.Ram
	}
	return 0
}

func (x *NodesCreateRequest) GetStorage() uint32 {
	if x != nil {
		return x.Storage
	}
	return 0
}

type NodesCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *NodesCreateResponse) Reset() {
	*x = NodesCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodes_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodesCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesCreateResponse) ProtoMessage() {}

func (x *NodesCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesCreateResponse.ProtoReflect.Descriptor instead.
func (*NodesCreateResponse) Descriptor() ([]byte, []int) {
	return file_nodes_api_proto_rawDescGZIP(), []int{1}
}

func (x *NodesCreateResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodesFindAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NodesFindAllRequest) Reset() {
	*x = NodesFindAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodes_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodesFindAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesFindAllRequest) ProtoMessage() {}

func (x *NodesFindAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesFindAllRequest.ProtoReflect.Descriptor instead.
func (*NodesFindAllRequest) Descriptor() ([]byte, []int) {
	return file_nodes_api_proto_rawDescGZIP(), []int{2}
}

type NodesFindAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *NodesFindAllResponse) Reset() {
	*x = NodesFindAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodes_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodesFindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesFindAllResponse) ProtoMessage() {}

func (x *NodesFindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesFindAllResponse.ProtoReflect.Descriptor instead.
func (*NodesFindAllResponse) Descriptor() ([]byte, []int) {
	return file_nodes_api_proto_rawDescGZIP(), []int{3}
}

func (x *NodesFindAllResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodesDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *UUID `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *NodesDeleteRequest) Reset() {
	*x = NodesDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodes_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodesDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesDeleteRequest) ProtoMessage() {}

func (x *NodesDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesDeleteRequest.ProtoReflect.Descriptor instead.
func (*NodesDeleteRequest) Descriptor() ([]byte, []int) {
	return file_nodes_api_proto_rawDescGZIP(), []int{4}
}

func (x *NodesDeleteRequest) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

type NodesDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NodesDeleteResponse) Reset() {
	*x = NodesDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodes_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodesDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesDeleteResponse) ProtoMessage() {}

func (x *NodesDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesDeleteResponse.ProtoReflect.Descriptor instead.
func (*NodesDeleteResponse) Descriptor() ([]byte, []int) {
	return file_nodes_api_proto_rawDescGZIP(), []int{5}
}

var File_nodes_api_proto protoreflect.FileDescriptor

var file_nodes_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3,
	0x02, 0x0a, 0x12, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x70, 0x76, 0x34, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x70, 0x76,
	0x34, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x71, 0x64, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x71, 0x64, 0x6e, 0x12, 0x27, 0x0a, 0x0f,
	0x73, 0x6b, 0x79, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x6b, 0x79, 0x68, 0x6f, 0x6f, 0x6b, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x70, 0x75, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0c, 0x63, 0x70, 0x75, 0x42, 0x61, 0x73, 0x65, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x61, 0x6c, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x6d, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x13, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x33, 0x0a, 0x14, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x12, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x02, 0x49,
	0x64, 0x22, 0x15, 0x0a, 0x13, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x67, 0x6f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_nodes_api_proto_rawDescOnce sync.Once
	file_nodes_api_proto_rawDescData = file_nodes_api_proto_rawDesc
)

func file_nodes_api_proto_rawDescGZIP() []byte {
	file_nodes_api_proto_rawDescOnce.Do(func() {
		file_nodes_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_nodes_api_proto_rawDescData)
	})
	return file_nodes_api_proto_rawDescData
}

var file_nodes_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nodes_api_proto_goTypes = []interface{}{
	(*NodesCreateRequest)(nil),   // 0: NodesCreateRequest
	(*NodesCreateResponse)(nil),  // 1: NodesCreateResponse
	(*NodesFindAllRequest)(nil),  // 2: NodesFindAllRequest
	(*NodesFindAllResponse)(nil), // 3: NodesFindAllResponse
	(*NodesDeleteRequest)(nil),   // 4: NodesDeleteRequest
	(*NodesDeleteResponse)(nil),  // 5: NodesDeleteResponse
	(*Node)(nil),                 // 6: Node
	(*UUID)(nil),                 // 7: UUID
}
var file_nodes_api_proto_depIdxs = []int32{
	6, // 0: NodesCreateResponse.nodes:type_name -> Node
	6, // 1: NodesFindAllResponse.nodes:type_name -> Node
	7, // 2: NodesDeleteRequest.Id:type_name -> UUID
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nodes_api_proto_init() }
func file_nodes_api_proto_init() {
	if File_nodes_api_proto != nil {
		return
	}
	file_generic_proto_init()
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_nodes_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodesCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodes_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodesCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodes_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodesFindAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodes_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodesFindAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodes_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodesDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodes_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodesDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nodes_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nodes_api_proto_goTypes,
		DependencyIndexes: file_nodes_api_proto_depIdxs,
		MessageInfos:      file_nodes_api_proto_msgTypes,
	}.Build()
	File_nodes_api_proto = out.File
	file_nodes_api_proto_rawDesc = nil
	file_nodes_api_proto_goTypes = nil
	file_nodes_api_proto_depIdxs = nil
}
