// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Encedeus/panel/ent/apikey"
	"github.com/Encedeus/panel/ent/predicate"
	"github.com/Encedeus/panel/ent/user"
	"github.com/google/uuid"
)

// ApiKeyUpdate is the builder for updating ApiKey entities.
type ApiKeyUpdate struct {
	config
	hooks    []Hook
	mutation *ApiKeyMutation
}

// Where appends a list predicates to the ApiKeyUpdate builder.
func (aku *ApiKeyUpdate) Where(ps ...predicate.ApiKey) *ApiKeyUpdate {
	aku.mutation.Where(ps...)
	return aku
}

// SetDescription sets the "description" field.
func (aku *ApiKeyUpdate) SetDescription(s string) *ApiKeyUpdate {
	aku.mutation.SetDescription(s)
	return aku
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (aku *ApiKeyUpdate) SetNillableDescription(s *string) *ApiKeyUpdate {
	if s != nil {
		aku.SetDescription(*s)
	}
	return aku
}

// ClearDescription clears the value of the "description" field.
func (aku *ApiKeyUpdate) ClearDescription() *ApiKeyUpdate {
	aku.mutation.ClearDescription()
	return aku
}

// SetIPAddresses sets the "ip_addresses" field.
func (aku *ApiKeyUpdate) SetIPAddresses(s []string) *ApiKeyUpdate {
	aku.mutation.SetIPAddresses(s)
	return aku
}

// AppendIPAddresses appends s to the "ip_addresses" field.
func (aku *ApiKeyUpdate) AppendIPAddresses(s []string) *ApiKeyUpdate {
	aku.mutation.AppendIPAddresses(s)
	return aku
}

// ClearIPAddresses clears the value of the "ip_addresses" field.
func (aku *ApiKeyUpdate) ClearIPAddresses() *ApiKeyUpdate {
	aku.mutation.ClearIPAddresses()
	return aku
}

// SetKey sets the "key" field.
func (aku *ApiKeyUpdate) SetKey(s string) *ApiKeyUpdate {
	aku.mutation.SetKey(s)
	return aku
}

// SetUserID sets the "user_id" field.
func (aku *ApiKeyUpdate) SetUserID(u uuid.UUID) *ApiKeyUpdate {
	aku.mutation.SetUserID(u)
	return aku
}

// SetUser sets the "user" edge to the User entity.
func (aku *ApiKeyUpdate) SetUser(u *User) *ApiKeyUpdate {
	return aku.SetUserID(u.ID)
}

// Mutation returns the ApiKeyMutation object of the builder.
func (aku *ApiKeyUpdate) Mutation() *ApiKeyMutation {
	return aku.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (aku *ApiKeyUpdate) ClearUser() *ApiKeyUpdate {
	aku.mutation.ClearUser()
	return aku
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aku *ApiKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, aku.sqlSave, aku.mutation, aku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aku *ApiKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := aku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aku *ApiKeyUpdate) Exec(ctx context.Context) error {
	_, err := aku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aku *ApiKeyUpdate) ExecX(ctx context.Context) {
	if err := aku.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aku *ApiKeyUpdate) check() error {
	if v, ok := aku.mutation.Key(); ok {
		if err := apikey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key": %w`, err)}
		}
	}
	if _, ok := aku.mutation.UserID(); aku.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "ApiKey.user"`)
	}
	return nil
}

func (aku *ApiKeyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := aku.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeUUID))
	if ps := aku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aku.mutation.Description(); ok {
		_spec.SetField(apikey.FieldDescription, field.TypeString, value)
	}
	if aku.mutation.DescriptionCleared() {
		_spec.ClearField(apikey.FieldDescription, field.TypeString)
	}
	if value, ok := aku.mutation.IPAddresses(); ok {
		_spec.SetField(apikey.FieldIPAddresses, field.TypeJSON, value)
	}
	if value, ok := aku.mutation.AppendedIPAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apikey.FieldIPAddresses, value)
		})
	}
	if aku.mutation.IPAddressesCleared() {
		_spec.ClearField(apikey.FieldIPAddresses, field.TypeJSON)
	}
	if value, ok := aku.mutation.Key(); ok {
		_spec.SetField(apikey.FieldKey, field.TypeString, value)
	}
	if aku.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikey.UserTable,
			Columns: []string{apikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aku.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikey.UserTable,
			Columns: []string{apikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aku.mutation.done = true
	return n, nil
}

// ApiKeyUpdateOne is the builder for updating a single ApiKey entity.
type ApiKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiKeyMutation
}

// SetDescription sets the "description" field.
func (akuo *ApiKeyUpdateOne) SetDescription(s string) *ApiKeyUpdateOne {
	akuo.mutation.SetDescription(s)
	return akuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (akuo *ApiKeyUpdateOne) SetNillableDescription(s *string) *ApiKeyUpdateOne {
	if s != nil {
		akuo.SetDescription(*s)
	}
	return akuo
}

// ClearDescription clears the value of the "description" field.
func (akuo *ApiKeyUpdateOne) ClearDescription() *ApiKeyUpdateOne {
	akuo.mutation.ClearDescription()
	return akuo
}

// SetIPAddresses sets the "ip_addresses" field.
func (akuo *ApiKeyUpdateOne) SetIPAddresses(s []string) *ApiKeyUpdateOne {
	akuo.mutation.SetIPAddresses(s)
	return akuo
}

// AppendIPAddresses appends s to the "ip_addresses" field.
func (akuo *ApiKeyUpdateOne) AppendIPAddresses(s []string) *ApiKeyUpdateOne {
	akuo.mutation.AppendIPAddresses(s)
	return akuo
}

// ClearIPAddresses clears the value of the "ip_addresses" field.
func (akuo *ApiKeyUpdateOne) ClearIPAddresses() *ApiKeyUpdateOne {
	akuo.mutation.ClearIPAddresses()
	return akuo
}

// SetKey sets the "key" field.
func (akuo *ApiKeyUpdateOne) SetKey(s string) *ApiKeyUpdateOne {
	akuo.mutation.SetKey(s)
	return akuo
}

// SetUserID sets the "user_id" field.
func (akuo *ApiKeyUpdateOne) SetUserID(u uuid.UUID) *ApiKeyUpdateOne {
	akuo.mutation.SetUserID(u)
	return akuo
}

// SetUser sets the "user" edge to the User entity.
func (akuo *ApiKeyUpdateOne) SetUser(u *User) *ApiKeyUpdateOne {
	return akuo.SetUserID(u.ID)
}

// Mutation returns the ApiKeyMutation object of the builder.
func (akuo *ApiKeyUpdateOne) Mutation() *ApiKeyMutation {
	return akuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (akuo *ApiKeyUpdateOne) ClearUser() *ApiKeyUpdateOne {
	akuo.mutation.ClearUser()
	return akuo
}

// Where appends a list predicates to the ApiKeyUpdate builder.
func (akuo *ApiKeyUpdateOne) Where(ps ...predicate.ApiKey) *ApiKeyUpdateOne {
	akuo.mutation.Where(ps...)
	return akuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (akuo *ApiKeyUpdateOne) Select(field string, fields ...string) *ApiKeyUpdateOne {
	akuo.fields = append([]string{field}, fields...)
	return akuo
}

// Save executes the query and returns the updated ApiKey entity.
func (akuo *ApiKeyUpdateOne) Save(ctx context.Context) (*ApiKey, error) {
	return withHooks(ctx, akuo.sqlSave, akuo.mutation, akuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (akuo *ApiKeyUpdateOne) SaveX(ctx context.Context) *ApiKey {
	node, err := akuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (akuo *ApiKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := akuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (akuo *ApiKeyUpdateOne) ExecX(ctx context.Context) {
	if err := akuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (akuo *ApiKeyUpdateOne) check() error {
	if v, ok := akuo.mutation.Key(); ok {
		if err := apikey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key": %w`, err)}
		}
	}
	if _, ok := akuo.mutation.UserID(); akuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "ApiKey.user"`)
	}
	return nil
}

func (akuo *ApiKeyUpdateOne) sqlSave(ctx context.Context) (_node *ApiKey, err error) {
	if err := akuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeUUID))
	id, ok := akuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := akuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikey.FieldID)
		for _, f := range fields {
			if !apikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := akuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := akuo.mutation.Description(); ok {
		_spec.SetField(apikey.FieldDescription, field.TypeString, value)
	}
	if akuo.mutation.DescriptionCleared() {
		_spec.ClearField(apikey.FieldDescription, field.TypeString)
	}
	if value, ok := akuo.mutation.IPAddresses(); ok {
		_spec.SetField(apikey.FieldIPAddresses, field.TypeJSON, value)
	}
	if value, ok := akuo.mutation.AppendedIPAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apikey.FieldIPAddresses, value)
		})
	}
	if akuo.mutation.IPAddressesCleared() {
		_spec.ClearField(apikey.FieldIPAddresses, field.TypeJSON)
	}
	if value, ok := akuo.mutation.Key(); ok {
		_spec.SetField(apikey.FieldKey, field.TypeString, value)
	}
	if akuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikey.UserTable,
			Columns: []string{apikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := akuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikey.UserTable,
			Columns: []string{apikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApiKey{config: akuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, akuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	akuo.mutation.done = true
	return _node, nil
}
