// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ApiKey is the predicate function for apikey builders.
type ApiKey func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
